FROM oven/bun:1.1

WORKDIR /app

COPY package.json bun.lockb tsconfig.json ./
COPY apps ./apps
COPY packages ./packages
COPY docker ./docker

RUN bun install --ignore-scripts
RUN cd /app/apps/web && bun run build

COPY docker/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 3000 3001

ENTRYPOINT ["/entrypoint.sh"]
